---@meta
-- Auto-generated by `zig build docs`. Do not edit by hand.
-- LuaCATS type definitions for the global `agate` object (lua-language-server).

---@alias agate.Layout
---| '"h_tiles"'
---| '"v_tiles"'
---| '"h_stack"'
---| '"v_stack"'
---| '"accordion"'
---| '"float"'
---| '"toggle"'

---@alias agate.Direction
---| '"left"'
---| '"right"'
---| '"up"'
---| '"down"'

---@alias agate.MonitorDir
---| '"next"'
---| '"prev"'
---| '"left"'
---| '"right"'
---| '"up"'
---| '"down"'

---@class agate.Config
---@field animation_duration? number Length of the frame animation in **milliseconds** (lower = faster; `0` disables). Only meaningful with `animations = true`. (default `150`)
---@field space_animation? string How much of the Space-switch transition plays: `"fast"`, `"very_fast"`, or `"instant"` (no perceptible animation). (default `"instant"`)
---@field gaps? number Pixels between adjacent tiles. (default `8`)
---@field outer_gaps? number Pixels inset from the screen edge. (default `8`)
---@field accordion_padding? number Stacked-window "peek": how far each window in a stack/accordion fans past the one in front. Alias: `accordion`. (default `40`)
---@field hyper? string[] Modifier set the `hyper` macro in key specs expands to. Any of: `ctrl`/`control`, `alt`/`opt`, `cmd`/`command`, `shift`. (default `{"ctrl","alt","cmd","shift"}`)
---@field hyper_key? string Physical key whose held state is treated as `hyper`, for remappers (lazykeys/Karabiner) that hide the real modifiers from the event tap. A key name like `"f18"`; empty disables. (default `"f18"`)
---@field small_screen? agate.SmallScreen Small Screen Mode (see agate.SmallScreen): workspaces on a small main display trade the split layout for an accordion, and back when a big display takes over. (default `{ enabled = true, layout = "h_accordion", max_width = 0 }`)
---@field animations? boolean Animate tiling frame changes instead of snapping: the final size applies instantly, the position glides over (60 Hz, ease-out, capped at 8 windows per flush with an automatic snap when an app is too busy to keep up). Speed via `animation_duration`. (default `false`)
---@field space_indicator? boolean Show the active space's number as a menu-bar status item. (default `true`)
---@field drag_preview? boolean While dragging a window, highlight the tile it will swap into on drop with a translucent overlay. (default `true`)
---@field smart_gaps? boolean When a workspace holds a single window, drop the outer gap so it fills the display edge-to-edge (Hyprland's `no_gaps_when_only`). (default `false`)

---@class agate.SmallScreen
---@field enabled? boolean Master switch (default `true`).
---@field layout? string Layout small workspaces get: any layout name (default `"h_accordion"`), or `"tabs"` for a zero-peek stack — full-area windows flipped through like tabs.
---@field max_width? number Width (points) at or under which a display counts as small, in addition to the built-in panel. `0` (default) = built-in display detection only.

---@class agate.Rule
---@field app? string POSIX extended regex matched against the owning application's name, e.g. `"^Music$"`.
---@field title? string POSIX extended regex matched against the window title.
---@field space? integer 1-based Space position (Mission Control order, fullscreen included) matched windows are sent to. Required unless `monitor` is given (then it defaults to that monitor's first Space).
---@field monitor? integer 1-based monitor (display order) the `space` position counts on; pins the app to that display. Omit for the focused display.
---@field follow? boolean Switch to that space along with the window (default `true`). Set `false` to route the window in the background — usually what you want when pinning to a monitor.
---@field floating? boolean Float matched windows when they appear (like `agate.toggle_float()` applied automatically) — tracked but lifted out of the tiling. Can be the rule's only effect (no `space` needed), or combined with a Space/monitor assignment.

---@class Agate
agate = {}

---Apply global configuration. Call once near the top of init.lua.
---@param config agate.Config Settings table (see agate.Config).
function agate.config(config) end

---Bind a key chord to an action.
---@param spec string Key chord, e.g. `"hyper+shift+l"`.
---@param action fun()|string A Lua callback, or a string command (see Commands below).
function agate.bind(spec, action) end

---Bind a trackpad swipe to an action. The swipe tracks live with a Liquid Glass HUD and fires once when you lift — drag far enough or flick fast, like native macOS. The system gestures on the same finger count must be off or moved to the other count in Trackpad settings.
---@param spec string Finger count (3 or 4) and direction, e.g. `"3:left"` or `"4:up"`.
---@param action fun()|string A Lua callback, or a string command (see Commands below).
function agate.gesture(spec, action) end

---Define a modal keybind group (Hyprland-style submap): a named table of `keyspec = action` entries that are live only while the mode is active. Enter with `agate.enter_mode(name)`, leave with `agate.exit_mode()`. While a mode is active only its bindings fire — global binds are suppressed and unbound keys pass through to the focused app. Bind `escape` to `agate.exit_mode` so there's always a way out.
---@param name string Mode name, referenced by `enter_mode`/`exit_mode` and the `mode <name>` command.
---@param bindings table Table mapping a key chord (e.g. `"h"`, `"shift+l"`) to a Lua function or string command.
function agate.mode(name, bindings) end

---Activate a mode defined with `agate.mode`. While active, only that mode's bindings fire; global binds are suppressed and unbound keys pass through. The active mode name shows in the menu-bar indicator.
---@param name string Name of a mode registered with `agate.mode`.
function agate.enter_mode(name) end

---Leave the active mode and return to the normal keymap. Bind this to `escape` inside a mode so there's always a way out.
function agate.exit_mode() end

---Focus the next/previous window among the focused window's siblings, wrapping at the edges — the natural motion through an accordion/stack (Small Screen Mode), bindable to a swipe or a key.
---@param dir "next"|"prev" Cycle direction.
function agate.cycle(dir) end

---Move focus to the nearest window in a direction, descending into and ascending out of nested containers (i3-style). Left/right traverse horizontal splits/stacks; up/down vertical ones.
---@param dir agate.Direction Direction to move focus.
function agate.focus(dir) end

---Set the focused container's layout (the focused window's parent), falling back to the workspace for top-level windows.
---@param mode agate.Layout Layout mode to apply.
function agate.layout(mode) end

---Combine the focused window with its neighbour into a nested container, for mixed layouts (e.g. a row whose one slot is a stack of two windows).
---@param dir agate.Direction Neighbour to combine with.
---@param mode? agate.Layout Layout of the new container. Default `v_stack`.
function agate.join(dir, mode) end

---Toggle "zoom fullscreen" for the focused window (yabai's `window --toggle zoom-fullscreen`): the window fills the whole space, overlapping the other tiles; toggle again to drop it back into the tiling. Not native macOS fullscreen — it stays on the same Space with no transition.
function agate.zoom_fullscreen() end

---Toggle floating for the focused window (yabai's `window --toggle float`): lift it out of the tiling so it keeps its own free position and size on top while the other tiles reflow without it; toggle again to drop it back into the layout. The window stays on the same Space and is still tracked, focusable, and closes normally.
function agate.toggle_float() end

---Run a shell command in the background, like skhd's `:` commands. The command line is handed to `$SHELL -c` (falling back to `/bin/sh -c`), so pipes, globs, and `&&` all work. agate does not wait for it — use it to launch apps or scripts from a keybind.
---@param cmd string The shell command line to run.
function agate.exec(cmd) end

---Switch to the Nth Space on the focused display. Counts every Space the swipe passes through, in Mission Control order — including native-fullscreen Spaces (so a fullscreened app at strip position N is reached by N).
---@param n integer 1-based Space position on the focused display, in Mission Control order (fullscreen Spaces included).
function agate.space(n) end

---Switch to the next Space on the focused display (one step in Mission Control order, fullscreen Spaces included).
function agate.space_next() end

---Switch to the previous Space on the focused display (one step in Mission Control order, fullscreen Spaces included).
function agate.space_prev() end

---Resize the focused tile, transferring the delta to its neighbour.
---@param dir agate.Direction Edge to grow toward.
---@param amount? number Pixels to resize by. Default 50.
function agate.resize(dir, amount) end

---Swap the focused window with its neighbour in a direction. Works across nested containers.
---@param dir agate.Direction Direction to move the window.
function agate.move(dir) end

---Send the focused window to user space N (does not follow focus). With a monitor argument, the space on that display.
---@param n integer 1-based Space position (Mission Control order, fullscreen included) to send the window to.
---@param monitor? integer 1-based monitor (display order) the position counts on. Omit for the focused display — pass it to assign the window to a Space on another monitor.
function agate.move_to_space(n, monitor) end

---Move keyboard focus to another display, raising its most-recently-used window (or warping the cursor to an empty display). No-op with a single display.
---@param dir agate.MonitorDir Which display to focus.
function agate.focus_monitor(dir) end

---Move the focused window to an adjacent display's visible space, tile it there, and follow focus to it.
---@param dir agate.MonitorDir Which display to move the window to.
function agate.move_to_monitor(dir) end

---Register a window assignment rule, like yabai's `rule --add`: windows whose app name/title match the given regexes are sent to a space (and optionally a specific monitor) and/or floated when they appear. At least one of `app`/`title` is required; both must match when both are given. Give `space`, `monitor`, `floating = true`, or a combination — a rule must have at least one effect. When several rules match a window, the last registered one wins.
---@param rule agate.Rule Rule table (see agate.Rule).
function agate.rule(rule) end

return agate
