---@meta
-- Auto-generated by `zig build docs`. Do not edit by hand.
-- LuaCATS type definitions for the global `agate` object (lua-language-server).

---@alias agate.Layout
---| '"h_tiles"'
---| '"v_tiles"'
---| '"h_stack"'
---| '"v_stack"'
---| '"accordion"'
---| '"float"'
---| '"toggle"'

---@alias agate.Direction
---| '"left"'
---| '"right"'
---| '"up"'
---| '"down"'

---@alias agate.MonitorDir
---| '"next"'
---| '"prev"'
---| '"left"'
---| '"right"'
---| '"up"'
---| '"down"'

---@class agate.Config
---@field gaps? number|table Pixels between tiles. A number sets both the inner gap and the screen-edge inset; a table `{ inner, outer, smart }` sets them separately (`smart` drops the outer gap when a workspace holds a single window). (default `8`)
---@field animations? boolean|number Animate tiling frame changes instead of snapping (the size applies instantly, the position glides). `true`/`false` toggles it at the default speed; a number sets the per-frame duration in **milliseconds** and enables it (lower = snappier, `0` = off). (default `false`)
---@field columns? table Flow strip tuning. `default_width` (0–1): the viewport fraction a freshly opened column targets. `min_width` (0–1): the soft bound — while every column fits at this width the strip tiles the whole screen, past that it scrolls (so it sets on-screen capacity, ≈`floor(1/min_width)`). `presets`: the widths `agate.column_width` cycles and the `"1/3"`/`"1/2"`/`"2/3"`/`"full"` names snap to. (default `{ default_width = 0.5, min_width = 0.22, presets = { 0.333, 0.5, 0.667, 1.0 } }`)
---@field peek? number How much of a hidden window stays visible (px): the accordion/stack fan (how far each stacked window peeks past the one in front) **and** the Flow strip's off-screen edge peek (an off-screen column kept clickable at the screen edge). Aliases: `accordion_padding`, `accordion`. (default `48`)
---@field hyper_key? agate.HyperKey Built-in hyper key (see agate.HyperKey), ported from LazyKeys. When enabled, agate remaps Caps Lock to F18 at the HID level (via `hidutil`) and treats a held Caps Lock as the modifier set in `keys` — for both agate keybindings and the focused app. The `hyper` macro in key specs expands to `keys`. (default `{ enabled = true, keys = {"ctrl","alt","cmd","shift"} }`)
---@field small_screen? agate.SmallScreen Small Screen Mode (see agate.SmallScreen): workspaces on a small main display trade the split layout for an accordion, and back when a big display takes over. (default `{ enabled = true, layout = "h_accordion", max_width = 0 }`)
---@field space_indicator? boolean Show the active space's number as a menu-bar status item. (default `true`)
---@field drag_preview? boolean While dragging a window, highlight the tile it will swap into on drop with a translucent overlay. (default `true`)
---@field swipe_scroll_fingers? integer Flow strip: number of fingers for the trackpad swipe that scrolls the strip live (drag the columns under your fingers, snapping to a column on release). Set 0 to disable. (default `3`)

---@class agate.SmallScreen
---@field enabled? boolean Master switch (default `true`).
---@field layout? string Layout small workspaces get: any layout name (default `"h_accordion"`), or `"tabs"` for a zero-peek stack — full-area windows flipped through like tabs.
---@field max_width? number Width (points) at or under which a display counts as small, in addition to the built-in panel. `0` (default) = built-in display detection only.

---@class agate.HyperKey
---@field enabled? boolean Master switch (default `true`). When on, agate remaps Caps Lock to F18 via `hidutil` and treats it as the hyper key; the remap is restored on exit. Turn it off to leave Caps Lock alone.
---@field keys? string[] Modifier set the held hyper key — and the `hyper` macro in key specs — expands to. Any of: `ctrl`/`control`, `alt`/`opt`, `cmd`/`command`, `shift`. Default `{"ctrl","alt","cmd","shift"}`.

---@class agate.Rule
---@field app? string POSIX extended regex matched against the owning application's name, e.g. `"^Music$"`.
---@field title? string POSIX extended regex matched against the window title.
---@field space? integer 1-based Space position (Mission Control order, fullscreen included) matched windows are sent to. Required unless `monitor` is given (then it defaults to that monitor's first Space).
---@field monitor? integer 1-based monitor (display order) the `space` position counts on; pins the app to that display. Omit for the focused display.
---@field follow? boolean Switch to that space along with the window (default `true`). Set `false` to route the window in the background — usually what you want when pinning to a monitor.
---@field floating? boolean Float matched windows when they appear (like `agate.toggle("float")` applied automatically) — tracked but lifted out of the tiling. Can be the rule's only effect (no `space` needed), or combined with a Space/monitor assignment.

---@class Agate
agate = {}

---Apply global configuration. Call once near the top of init.lua.
---@param config agate.Config Settings table (see agate.Config).
function agate.config(config) end

---Bind a key chord to an action.
---@param spec string Key chord, e.g. `"hyper+shift+l"`.
---@param action fun()|string A Lua callback, or a string command (see Commands below).
function agate.bind(spec, action) end

---Bind a trackpad swipe to an action. The swipe tracks live with a Liquid Glass HUD and fires once when you lift — drag far enough or flick fast, like native macOS. The system gestures on the same finger count must be off or moved to the other count in Trackpad settings.
---@param spec string Finger count (3 or 4) and direction, e.g. `"3:left"` or `"4:up"`.
---@param action fun()|string A Lua callback, or a string command (see Commands below).
function agate.gesture(spec, action) end

---Run a Lua callback whenever agate performs an action. The callback receives a single table describing the event. Register more than one for the same event and they all run, in order. Events: `space_changed` (`{ space = N }` — the new 1-based Space position), `mode_changed` (`{ mode = "name" }` on enter, `{ mode = nil }` on exit), `window_created` / `window_destroyed` (`{ window = id }`). Use it to e.g. run a shell command on every Space switch via `agate.exec`.
---@param event string Event name: `"space_changed"`, `"mode_changed"`, `"window_created"`, or `"window_destroyed"`.
---@param callback fun(event:table) A Lua function called with a table of event data (fields depend on the event).
function agate.on(event, callback) end

---Define a modal keybind group (Hyprland-style submap): a named table of `keyspec = action` entries that are live only while the mode is active. Enter with `agate.enter_mode(name)`, leave with `agate.exit_mode()`. While a mode is active only its bindings fire — global binds are suppressed and unbound keys pass through to the focused app. Bind `escape` to `agate.exit_mode` so there's always a way out.
---@param name string Mode name, referenced by `enter_mode`/`exit_mode` and the `mode <name>` command.
---@param bindings table Table mapping a key chord (e.g. `"h"`, `"shift+l"`) to a Lua function or string command.
function agate.mode(name, bindings) end

---Activate a mode defined with `agate.mode`. While active, only that mode's bindings fire; global binds are suppressed and unbound keys pass through. The active mode name shows in the menu-bar indicator.
---@param name string Name of a mode registered with `agate.mode`.
function agate.enter_mode(name) end

---Leave the active mode and return to the normal keymap. Bind this to `escape` inside a mode so there's always a way out.
function agate.exit_mode() end

---Move keyboard focus. A direction (`left`/`right`/`up`/`down`) moves to the nearest window that way, descending into and ascending out of nested containers (i3-style; left/right traverse horizontal splits/stacks, up/down vertical ones). `"next"`/`"prev"` instead cycle through the focused window's siblings, wrapping at the edges — the natural motion through an accordion/stack.
---@param target agate.Direction|string A direction to move focus, or `"next"`/`"prev"` to cycle siblings.
function agate.focus(target) end

---Set the focused Flow-strip column's internal tiling layout. On a multi-window column it re-tiles immediately; on a single-window column there's nothing to restyle yet, so it *arms* the column (i3-style "split") — the next window you open tiles into this column with the chosen layout instead of starting its own column on the strip. The column keeps collecting opened windows while focused; `agate.expel` ejects one back to its own column.
---@param mode agate.Layout Layout mode to apply (`v_split`/`h_split`/`accordion`/`toggle`/…).
function agate.layout(mode) end

---Combine the focused window with its neighbour into a nested container, for mixed layouts (e.g. a row whose one slot is a stack of two windows).
---@param dir agate.Direction Neighbour to combine with.
---@param mode? agate.Layout Layout of the new container. Default `v_stack`.
function agate.join(dir, mode) end

---Toggle a state on the focused window. `"fullscreen"` (yabai's zoom-fullscreen) makes it fill the whole space over the other tiles, with no Space transition; `"float"` lifts it out of the tiling to keep its own free position and size on top while the rest reflow. Toggle again to undo; the window stays on the same Space, tracked and focusable, either way.
---@param what string `"fullscreen"` or `"float"`.
function agate.toggle(what) end

---Flow strip: set or cycle the focused column's width. `"wider"`/`"narrower"` (aliases `"next"`/`"prev"`) step through the column presets; `"full"`, `"half"`, or a fraction like `"1/3"`/`"2/3"` set it directly; `"fit"` re-equalizes *every* column so they tile the viewport evenly (balanced classic tiling, undoing manual widths). Only `"fit"` touches the neighbours — the rest change just the focused column.
---@param target string `"wider"`/`"narrower"`/`"next"`/`"prev"`, `"fit"`, or a width: `"full"`, `"half"`, `"1/3"`, `"1/2"`, `"2/3"`, a fraction `"a/b"`, or a number (`0.4`, or `40` for 40%).
function agate.column_width(target) end

---Flow strip: scroll or jump along the strip. `"left"`/`"right"` step focus to the adjacent column (auto-scrolling it into view), `"start"`/`"end"` focus the first/last column, `"center"` centers the focused column.
---@param target "left"|"right"|"start"|"end"|"center" Where to scroll.
function agate.scroll(target) end

---Flow strip: pull the adjacent column into the focused column, merging the two into a single vertical split (niri's "consume into column"). The focused window stays focused.
---@param dir agate.Direction Which neighbour column to absorb.
function agate.consume(dir) end

---Flow strip: eject the focused window out of its column into its own column on the strip (the inverse of `consume`).
---@param dir agate.Direction `"left"` ejects before the column, otherwise after it.
function agate.expel(dir) end

---Run a shell command in the background, like skhd's `:` commands. The command line is handed to `$SHELL -c` (falling back to `/bin/sh -c`), so pipes, globs, and `&&` all work. agate does not wait for it — use it to launch apps or scripts from a keybind.
---@param cmd string The shell command line to run.
function agate.exec(cmd) end

---Switch Space on the focused display: a 1-based position jumps there directly, or `"next"`/`"prev"` step one Space over. Counts every Space in Mission Control order, including native-fullscreen Spaces (so a fullscreened app at strip position N is reached by N).
---@param target integer|string A 1-based Space position (Mission Control order, fullscreen Spaces included), or `"next"`/`"prev"` to step.
function agate.space(target) end

---Resize the focused tile, transferring the delta to its neighbour. Pass `"smart"` (recommended) to resize along the focused window's container axis without picking an edge: a positive `amount` grows it, a negative one shrinks it, taking from whichever neighbour exists — so the same binding always enlarges/shrinks the focused window wherever it sits. A direction (`left`/`right`/`up`/`down`) instead grows the window toward that edge, by stealing from the neighbour there.
---@param target agate.Direction|string `"smart"` to resize along the container axis, or an edge (`left`/`right`/`up`/`down`) to grow toward.
---@param amount? number Pixels to resize by. Default 50. With `"smart"`, a negative value shrinks.
function agate.resize(target, amount) end

---Move the focused window. A direction (`left`/`right`/`up`/`down`) swaps it with its neighbour that way (across nested containers). `move("space", n [, monitor])` sends it to Space `n` (optionally on a given 1-based monitor) without following focus. `move("monitor", dir)` moves it to an adjacent display's visible Space, tiles it there, and follows focus over.
---@param target agate.Direction|string A direction to swap toward, or `"space"`/`"monitor"` to relocate the window (see the extra args).
---@param arg? integer|agate.MonitorDir With `"space"`: the 1-based Space position. With `"monitor"`: the display direction.
---@param monitor? integer With `"space"`: an optional 1-based monitor the position counts on (omit for the focused display).
function agate.move(target, arg, monitor) end

---Move keyboard focus to another display, raising its most-recently-used window (or warping the cursor to an empty display). No-op with a single display.
---@param dir agate.MonitorDir Which display to focus.
function agate.focus_monitor(dir) end

---Register a window assignment rule, like yabai's `rule --add`: windows whose app name/title match the given regexes are sent to a space (and optionally a specific monitor) and/or floated when they appear. At least one of `app`/`title` is required; both must match when both are given. Give `space`, `monitor`, `floating = true`, or a combination — a rule must have at least one effect. When several rules match a window, the last registered one wins.
---@param rule agate.Rule Rule table (see agate.Rule).
function agate.rule(rule) end

return agate
