---@meta
-- Auto-generated by `zig build docs` from `tools/gen_docs.zig`. Do not edit by hand.
-- LuaCATS type definitions for the global `agate` object (lua-language-server).

---@alias agate.Direction
---| '"left"'
---| '"right"'
---| '"up"'
---| '"down"'

---@alias agate.Layout
---| '"h_tiles"'
---| '"v_tiles"'
---| '"h_stack"'
---| '"v_stack"'
---| '"accordion"'
---| '"float"'
---| '"toggle"'

---@class agate.Config
---@field gaps? number Pixels between adjacent tiles. (default `8`)
---@field outer_gaps? number Pixels inset from the screen edge. (default `8`)
---@field accordion_padding? number Stacked-window "peek": how far each window in a stack/accordion fans past the one in front. Alias: `accordion`. (default `40`)
---@field hyper? string[] Modifier set the `hyper` macro in key specs expands to. Any of: `ctrl`/`control`, `alt`/`opt`, `cmd`/`command`, `shift`. (default `{"ctrl","alt","cmd","shift"}`)
---@field hyper_key? string Physical key whose held state is treated as `hyper`, for remappers (lazykeys/Karabiner) that hide the real modifiers from the event tap. A key name like `"f18"`; empty disables. (default `"f18"`)

---@class Agate
agate = {}

---Apply global configuration. Call once near the top of init.lua.
---@param config agate.Config Settings table (see agate.Config).
function agate.config(config) end

---Bind a key chord to an action.
---@param spec string Key chord, e.g. `"hyper+shift+l"`.
---@param action fun()|string A Lua callback, or a string command (see Commands below).
function agate.bind(spec, action) end

---Move focus to the nearest window in a direction, descending into and ascending out of nested containers (i3-style). Left/right traverse horizontal splits/stacks; up/down vertical ones.
---@param dir agate.Direction Direction to move focus.
function agate.focus(dir) end

---Set the focused container's layout (the focused window's parent), falling back to the workspace for top-level windows.
---@param mode agate.Layout Layout mode to apply.
function agate.layout(mode) end

---Resize the focused tile, transferring the delta to its neighbour.
---@param dir agate.Direction Edge to grow toward.
---@param amount? number Pixels to resize by. Default 50.
function agate.resize(dir, amount) end

---Swap the focused window with its neighbour in a direction. Works across nested containers.
---@param dir agate.Direction Direction to move the window.
function agate.move(dir) end

---Combine the focused window with its neighbour into a nested container, for mixed layouts (e.g. a row whose one slot is a stack of two windows).
---@param dir agate.Direction Neighbour to combine with.
---@param mode? agate.Layout Layout of the new container. Default `v_stack`.
function agate.join(dir, mode) end

---Switch to user space N on the focused display.
---@param n integer 1-based user-space index on the focused display.
function agate.space(n) end

---Switch to the next user space on the focused display.
function agate.space_next() end

---Switch to the previous user space on the focused display.
function agate.space_prev() end

---Send the focused window to user space N (does not follow focus).
---@param n integer 1-based user-space index to send the window to.
function agate.move_to_space(n) end

return agate
